.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EDITRA 1 "May  3, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
editra \- Simple multi-platform text editor
.SH SYNOPSIS
.B Editra
.RI [OPTIONS] \ \  [files ... ]
.br
.SH DESCRIPTION
\fBeditra\fP is a multi-platform text editor with an implementation that focuses on creating an easy to use interface and features that aid in code development. Currently it supports syntax highlighting and variety of other useful features for over 60 programming languages.
.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-c, \-\-confdir
Set custom configuration directory at runtime
.TP
.B \-d, \-\-debug
Turn on console debugging
.TP
.B \-\-auth
Print the ipc server info
.TP
.B \-p, \-\-profileOut
Turn on console debugging
.SH SEE ALSO
.BR baz (1).
.br
.SH AUTHOR
editra was written by Cody Precord <cprecord@editra.org>.
.PP
This manual page was written by Alejandro Garrido Mota <garridomota@gmail.com>,
for the Debian project (and may be used by others).
